name: fortnite_2
description: A Package for using the unofficial Epicgames/Fortnite API. Perform user user specific actions and get user data like skins etc..
version: 1.0.2
repository: https://github.com/oxelf/fortnite_2.0

environment:
    sdk: ">=2.15.1 <3.0.0"

dependencies:
    logging: ^1.0.2
    dio: ^4.0.4
    numeral: ^1.2.5
    http: ^0.13.5

dev_dependencies:
    lints: ^1.0.0
